# Generated by Django 4.2.21 on 2025-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='sdsodjioefo', max_length=150),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
