# Generated by Django 4.2.21 on 2025-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='end_date',
            field=models.CharField(default='None', max_length=12),
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='jobs',
            name='short_description',
            field=models.TextField(default='None'),
        ),
    ]
