# Generated by Django 4.2.21 on 2025-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jobs_end_date_jobs_location_jobs_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='end_date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='short_description',
            field=models.TextField(),
        ),
    ]
