# Generated by Django 4.2.21 on 2025-06-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_jobs_end_date_alter_jobs_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='end_date',
            new_name='end',
        ),
    ]
