# Generated by Django 4.2.21 on 2025-06-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='jid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.jobs'),
        ),
    ]
