# Generated by Django 4.2.21 on 2025-06-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_applications_jid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='path',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='jid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobs'),
        ),
    ]
