# Generated by Django 4.2.21 on 2025-06-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_applications_path_alter_applications_jid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='applications',
            name='path',
            field=models.TextField(),
        ),
    ]
