# Generated by Django 4.2.21 on 2025-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_jobs_application_deadline_jobs_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='cover_letter',
            field=models.TextField(default='Not provided'),
        ),
    ]
